// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5B-vHhFH5ubQI2-l86WrgyzN3e8jqT4I',
    appId: '1:33250084247:web:1cbb1bb97f39b9cb4170d2',
    messagingSenderId: '33250084247',
    projectId: 'safemenu-3b8f7',
    authDomain: 'safemenu-3b8f7.firebaseapp.com',
    storageBucket: 'safemenu-3b8f7.firebasestorage.app',
    measurementId: 'G-LVD39WVCEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC3H-GUbxGyuKNBZYyiE6eZazkTKwzghY',
    appId: '1:33250084247:android:e65ba1f6a131858e4170d2',
    messagingSenderId: '33250084247',
    projectId: 'safemenu-3b8f7',
    storageBucket: 'safemenu-3b8f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ02zspR-Dlvxzrg6HmFP0P9NTDMxECps',
    appId: '1:33250084247:ios:d7b28e699f19033b4170d2',
    messagingSenderId: '33250084247',
    projectId: 'safemenu-3b8f7',
    storageBucket: 'safemenu-3b8f7.firebasestorage.app',
    iosBundleId: 'com.example.safemenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ02zspR-Dlvxzrg6HmFP0P9NTDMxECps',
    appId: '1:33250084247:ios:d7b28e699f19033b4170d2',
    messagingSenderId: '33250084247',
    projectId: 'safemenu-3b8f7',
    storageBucket: 'safemenu-3b8f7.firebasestorage.app',
    iosBundleId: 'com.example.safemenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5B-vHhFH5ubQI2-l86WrgyzN3e8jqT4I',
    appId: '1:33250084247:web:2c508cc6f6da78af4170d2',
    messagingSenderId: '33250084247',
    projectId: 'safemenu-3b8f7',
    authDomain: 'safemenu-3b8f7.firebaseapp.com',
    storageBucket: 'safemenu-3b8f7.firebasestorage.app',
    measurementId: 'G-52WQDCWJX3',
  );

}